# Server Configuration 

server:
  port : 9292
  

# Eureka Client Discovery Configuration
eureka:
  client:
    register-with-eureka: true
    service-url: 
      defaultZone :  http://localhost:8761/eureka
