server:
  port: 9191
  
  
 
# Enabling Eureka Server Support
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defualtZone : http://localhost:8761/eureka