
spring:
  application:
    name : ONLINE_API_GATEWAY


# Configuring Server Port
server:
  port: 8088

# Eureka Server Configuration
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone : http://localhost:8761/eureka

# Configuration Zuul 

zuul:
  routes:
    organizationservices : /organization/*
    inventoryservice : /inventory/*
    
    
     






